package timeLapse.resources.persistenceDTO;

// Generated 13-oct-2009 23:10:27 by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TlpRol generated by hbm2java
 */
@Entity
@Table(name = "tlp_rol", catalog = "timelapse")
public class TlpRol implements java.io.Serializable {

	private String oid;
	private String nombre;
	private String descripcion;
	private Integer grado;
	private List<TldUsuario> tldUsuarios = new ArrayList<TldUsuario>(0);
	private List<TlrPermiso> tlrPermisos = new ArrayList<TlrPermiso>(0);

	public TlpRol() {
	}

	public TlpRol(String oid, String nombre) {
		this.oid = oid;
		this.nombre = nombre;
	}

	public TlpRol(String oid, String nombre, String descripcion, Integer grado,
			List<TldUsuario> tldUsuarios, List<TlrPermiso> tlrPermisos) {
		this.oid = oid;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.grado = grado;
		this.tldUsuarios = tldUsuarios;
		this.tlrPermisos = tlrPermisos;
	}

	@Id
	@Column(name = "oid", unique = true, nullable = false, length = 32)
	public String getOid() {
		return this.oid;
	}

	public void setOid(String oid) {
		this.oid = oid;
	}

	@Column(name = "nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "grado")
	public Integer getGrado() {
		return this.grado;
	}

	public void setGrado(Integer grado) {
		this.grado = grado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tlpRol")
	public List<TldUsuario> getTldUsuarios() {
		return this.tldUsuarios;
	}

	public void setTldUsuarios(List<TldUsuario> tldUsuarios) {
		this.tldUsuarios = tldUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tlpRol")
	public List<TlrPermiso> getTlrPermisos() {
		return this.tlrPermisos;
	}

	public void setTlrPermisos(List<TlrPermiso> tlrPermisos) {
		this.tlrPermisos = tlrPermisos;
	}

}
